### ISSUE TITLE
compatibility `networkx` and `python3.9`

### ISSUE THREAD

**Issue by donghwan-shin** [vgarousi/GaugeDependExtended#1]
Thanks for the great work!

I followed the instruction and faced an issue:
```bash
(venv) ➜  GaugeDependExtended git:(main) ✗ python application/main.py    
Traceback (most recent call last):
  File "/Users/donghwan.shin/Repositories/GaugeDependExtended/application/main.py", line 1, in <module>
    from application.UI import MainWindow
  File "/Users/donghwan.shin/Repositories/GaugeDependExtended/venv/lib/python3.9/site-packages/application/UI/MainWindow.py", line 10, in <module>
    from application.smells.smellController import SmellController
  File "/Users/donghwan.shin/Repositories/GaugeDependExtended/venv/lib/python3.9/site-packages/application/smells/smellController.py", line 11, in <module>
    from networkx import nx
ImportError: cannot import name 'nx' from 'networkx' (/Users/donghwan.shin/Repositories/GaugeDependExtended/venv/lib/python3.9/site-packages/networkx/__init__.py)
```

Here, I am using the following versions:
```bash
(venv) ➜  GaugeDependExtended git:(main) ✗ python -V      
Python 3.9.1
```

```bash
(venv) ➜  GaugeDependExtended git:(main) ✗ pip3 freeze
appnope==0.1.2
asttokens==2.0.5
backcall==0.2.0
beautifulsoup4==4.10.0
black==22.1.0
bs4==0.0.1
click==8.0.3
decorator==5.1.1
executing==0.8.2
GaugeExplorer==0.0.1
importlib-metadata==4.11.1
ipython==8.0.1
jedi==0.18.1
Jinja2==3.0.3
jsonpickle==2.1.0
Markdown==3.3.6
MarkupSafe==2.1.0
matplotlib-inline==0.1.3
mypy-extensions==0.4.3
networkx==2.6.3
parso==0.8.3
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==2.5.0
prompt-toolkit==3.0.28
ptyprocess==0.7.0
pure-eval==0.2.2
Pygments==2.11.2
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.1
PyQtWebEngine==5.15.5
PyQtWebEngine-Qt5==5.15.2
pyvis==0.1.9
PyYAML==5.3.1
six==1.16.0
soupsieve==2.3.1
stack-data==0.2.0
tomli==2.0.1
traitlets==5.1.1
typing-extensions==4.1.1
wcwidth==0.2.5
zipp==3.7.0
```

So, I downgrade the `networkx` version from `2.6.3` to `2.5` and it worked well. You may want to update `requirements.txt` to have `networkx==2.5`. 

Thanks!

**Comment by vgeruslu** [comment]
Many thanks Donghwan for your nice feedback and comments to make the above update.

Cameron and I will look into the vcomment.

Note: We are glad that the tool has provided use for your context...
